config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home/index'
  root 'home#index'

  get 'login', to: 'sessions#login'

  get 'users/profile'
  get '/users/:id/mypictures', to: 'users#mypictures'

  get 'pictures/new'

  resources :users do
    resources :pictures do
      resources :comments
      resources :votes
    end
  end
  resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :picture
  belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord # :nodoc:
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  validates :path, presence: true

  def count_votes
    count = 0
    votes.each do |vote|
      count += vote.vote_type.to_i
    end

    count
  end
end

app/models/user.rb
class User < ApplicationRecord # :nodoc:
  has_secure_password
  has_many :pictures, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  validates :username, presence: true
  validates :username, uniqueness: true
  validates :email, presence: true
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/controllers/application_controller.rb
# ApplicationController
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/comments_controller.rb
# CommentsController class
# author: Lukas Bischof
class CommentsController < ApplicationController
  before_action :find_comment, only: [:destroy]

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def create
    @picture = Picture.find(params[:picture_id])
    @comment = @picture.comments.create(content: comment_params[:content], user_id: params[:user_id])
    if @comment
      respond_to_successful_creation params, @picture
    else
      redirect_to root_path
    end
  end

  def respond_to_successful_creation(params, picture)
    respond_to do |format|
      format.html do
        redirect_to url_for(action: 'show',
                            controller: 'pictures',
                            id: params[:picture_id].to_s,
                            user_id: picture.user.id)
      end
      format.json { render json: { 'success' => 'created' } }
      format.js
    end
  end

  def destroy
    if destroy_comment @comment, @comment.user, @comment.picture
      respond_to_destroy_success
    else
      respond_to_destroy_failure
    end
  end

  def destroy_comment(comment, user, picture)
    comment.destroy if user == current_user || picture.user == current_user
    false
  end

  def respond_to_destroy_success
    respond_to do |format|
      format.html { redirect_to get_pic_url @comment.picture.id, @comment.picture.user.id }
      format.js
    end
  end

  def respond_to_destroy_failure
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def get_pic_url(picid, userid)
    url_for(
      action: 'show',
      controller: 'pictures',
      id: picid.to_s,
      user_id: userid.to_s
    )
  end
end

app/controllers/home_controller.rb
# Home controller for index page
class HomeController < ApplicationController
  def index
    query = '
        (SELECT sum(vote_type)
        FROM votes
        WHERE votes.picture_id=pictures.id) DESC'
    @all_pictures = Picture.order(query)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController # :nodoc:
  before_action :retrieve_user, only: %i[show create destroy]
  before_action :test_is_owner, only: %i[show destroy]

  def retrieve_user
    @user = User.find(params[:user_id])
  end

  def test_is_owner
    @is_owner = @user == current_user
  end

  def new
    @picture = Picture.new
  end

  def show
    @picture = @user.pictures.includes(:comments).find(params[:id])

    @votes_count = 0
    @votes_count = @picture.count_votes

    respond_to do |format|
      format.html do
        @already_voted = Vote.exists?(picture_id: @picture.id,
                                      user_id: current_user.id)
      end
      format.json { render json: @picture }
    end
  end

  def create
    return unless @user == current_user

    uploaded_io = picture_params[:picture]
    new_filename = generate_filename(uploaded_io)
    File.open(Rails.root.join('public', 'uploads', new_filename), 'wb') do |f|
      f.write(uploaded_io.read)

      @user.pictures.create(path: new_filename)

      redirect_to root_path
    end
  end

  def destroy
    if @is_owner
      picture = Picture.find(params[:id])
      picture.destroy
    end

    redirect_to home_index_path
  end

  private

  def picture_params
    params.require(:picture).permit(:picture)
  end

  def generate_filename(uploaded_io)
    "#{@user.id}#{Time.now.to_i}_#{uploaded_io.original_filename.strip.delete(' ')}"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController # :nodoc:
  def login; end

  def create
    user = User.find_by(username: params[:username])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      @message = 'Username or password invalid'

      render 'login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, params: { msg: 'Successfully logged out' }
  end
end

app/controllers/users_controller.rb
# UsersController to manage user requests
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    redirect_to 'new' # Hack to prevent the redirection when the form had errors and you reload it
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      redirect_to login_path
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    @success_message = 'Successfully saved user' if @user.update(user_params)

    render 'profile'
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def profile
    @user = current_user
  end

  def mypictures; end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController # :nodoc:
  def create
    type = vote_params[:type].to_i.positive? ? '1' : '-1'

    picture = Picture.find(params[:picture_id])
    if picture.votes.create(vote_type: type, user_id: params[:user_id])
      redirect_to url_for(pictures_url(params[:picture_id].to_s, picture.user.id))
    else
      redirect_to root_path
    end
  end

  def vote_params
    params.require(:vote).permit(:type)
  end

  def pictures_url(id, userid)
    {
      action: 'show',
      controller: 'pictures',
      id: id,
      user_id: userid
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_comment.html.erb
<% if comment.user != nil %>
    <div class="panel panel-default comment-panel copyable" id="<%= dom_id(comment) %>">
        <div class="panel-body">
            <p>
                <strong class="comment-user-username"><%= comment.user.username %></strong>
                <strong class="comment-created-at"> on <%= comment.created_at %>:</strong>
            </p>
            <p class="comment-content"><%= comment.content %></p>
            <p class="del-button">
                <% if comment.user == current_user or @picture.user == current_user %>
                    <br />
                    <%= link_to('Delete comment', {
                        :action=>"destroy",
                        :controller=>"comments",
                        :id=>"#{comment.id}",
                        :user_id=>"#{comment.user.id}",
                        :picture_id=>"#{@picture.id}"
                    }, class: 'btn btn-danger', method: :delete, remote: true) %>
                <% end %>
            </p>
        </div>
    </div>
<% end %>

app/views/comments/create.js.erb
function E(a) {
  return document.createElement(a)
}

HTMLElement.prototype.cls = function cls() {
  if (arguments.length == 0)
    return;

  newCls = arguments[0] instanceof Array ? arguments[0] : arguments;
  for (var i = 0; i < newCls.length; i++) {
    this.classList.add(newCls[i]);
  }

  return this;
};

HTMLElement.prototype.add = function add(child) {
  this.appendChild(child);
  return this;
};

HTMLElement.prototype.href = function href(h) {
  this.href = h;
  return this;
};

HTMLElement.prototype.text = function(txt) {
  this.add(document.createTextNode(txt));
};



function main() {
  console.log("Comment was created <%= @comment.inspect %>");
  <% has_delete_button = @comment.user == current_user or @picture.user == current_user %>

  var copiedNode = cloneNode();
  window.copiedNode = copiedNode;
  console.log(copiedNode);

  copiedNode.querySelector(".comment-user-username").text("<%= @comment.user.username %>");
  copiedNode.querySelector(".comment-created-at").text("<%= @comment.created_at %>");
  copiedNode.querySelector(".comment-content").text("<%= @comment.content %>");

  document.querySelector("#container-comments-container-wrapping-comments").add(copiedNode);
}

function cloneNode() {
  var copy = document.querySelector(".copyable").cloneNode(true);
  // copy.innerHTML = document.querySelector(".copyable");

  return copy;
}

<% if has_delete_button %>
  function deleteButton() {
    <% path = user_picture_comment_path(@comment.user.id, @picture, @comment) %>

    var button = E("a")
                 .cls("btn", "btn-default")
                 .href("<%= path %>")
  }
<% end %>

main();

app/views/comments/destroy.js.erb
var id = "<%= dom_id(@comment) %>";
var transitionDuration = 1000;
var el = document.getElementById(id)

el.classList.add("fade-out");

setTimeout(function(){
  el.parentElement.removeChild(el);
}, transitionDuration);

app/views/home/index.html.erb
<% provide(:title, 'Home') %>

<!-- <% if current_user %>
    <h1>Welcome <%= current_user.username %></h1>

    <% current_user.pictures.each do |p| %>
        <div class="image-container col-md-6"
            style="background: url(<%= "/uploads/#{p.path}" %>)"
            onclick="redirect('<%= url_for [current_user, p] %>')">

        </div>
    <% end %>
<% else %>
    <h1>Welcome</h1>
<% end %> -->


<% if current_user %>
    <% @all_pictures.each do |p| %>
        <div class="image-container col-md-6"
            style="background: url(<%= "/uploads/#{p.path}" %>)"
            onclick="redirect('<%= url_for [p.user, p] %>')">
            
        </div>
    <% end %>
<% else %>
    <% @all_pictures.each do |p| %>
        <div class="image-container col-md-6"
            style="background: url(<%= "/uploads/#{p.path}" %>)"
            onclick="redirect('<%= url_for(
              controller: 'sessions',
              action: 'login',
              msg: 'Please sign in to view this image'
            ) %>')">

        </div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Privagram |
      <%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to(root_path) do %>
        <div class="itm logo">Privagram</div>
      <% end %>

      <% if current_user %>
        <%= link_to(session_path("current"), method: 'delete') do %>
          <div class="itm right">Logout</div>
        <% end %>
        <%= link_to({controller: "users", action: "profile"}) do %>
          <div class="itm right">Profil</div>
        <% end %>
        <%= link_to({controller: "pictures", action: "new"}) do %>
          <div class="itm right">Upload</div>
        <% end %>
        <%= link_to({controller: "users", action: "mypictures", id: current_user.id}) do %>
          <div class="itm right">My Pictures</div>
        <% end %>
      <% else %>
        <%= link_to(login_path) do %>
          <div class="itm right login">Login</div>
        <% end %>
        <%= link_to(new_user_path) do %>
          <div class="itm right register">Register</div>
        <% end %>
      <% end %>
    </nav>
    <main>
      <div id="main-wrapper">
        <% if params[:msg] %>
          <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= params[:msg] %>
          </div>
        <% end %>

        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/pictures/new.html.erb
<% provide(:title, "Upload") %>

<div class="form-container">
    <h1>Upload</h1>

    <br />
    <div class="form-group">
        <%= form_for [current_user, current_user.pictures.build] do |f| %>
            <%= f.file_field :picture %>
            <br />
            <%= f.submit 'Upload file', class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/pictures/show.html.erb
<% provide(:title, "Detail") %>

<div class="image-presenter">
    <%= image_tag "/uploads/#{@picture.path}" %>
</div>

<br />

<p>Picture from <%= @picture.user.username %>, uploaded on <%= @picture.created_at %></p>
<div class="col-md-8">
    <div class="panel panel-primary comments-panel">
        <div class="panel-heading">
            <h3 class="panel-title">Comments</h3>
        </div>
        <div class="panel-body">
            <div class="comment-area">
                <div class="form-group">
                    <%= form_for [current_user, @picture, @picture.comments.build], remote: true do |f| %>
                        <%= f.label :content %>
                        <%= f.text_area :content, class: 'form-control', autofocus: true %>

                        <br />
                        <%= f.submit "Save comment", class: 'btn btn-default' %>
                    <% end %>
                </div>

                <br />
                <h3>Other comments</h3>

                <div id="container-comments-container-wrapping-comments">
                  <%= render @picture.comments %>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col-md-4">
    <div class="panel panel-primary comments-panel">
        <div class="panel-heading">
            <h3 class="panel-title">Votes</h3>
        </div>
        <div class="panel-body">
            <div class="vote-area">
                <%
                    disabled_class = @already_voted ? 'disabled' : ''
                    votes_count_class = @votes_count.negative? ? 'neg' : ''
                %>
                <%= link_to({
                        :action=>"create",
                        :controller=>"votes",
                        :user_id=>"#{current_user.id}",
                        :picture_id=>"#{@picture.id}",
                        :vote => {
                            type: 1
                        }
                    }, class: "btn btn-default #{disabled_class}", method: :post) do  %>
                    <span class="glyphicon glyphicon-thumbs-up"></span>
                <% end %>

                <%= link_to({
                        :action=>"create",
                        :controller=>"votes",
                        :user_id=>"#{current_user.id}",
                        :picture_id=>"#{@picture.id}",
                        :vote => {
                            type: -1
                        }
                    }, class: "btn btn-default #{disabled_class}", method: :post) do  %>
                    <span class="glyphicon glyphicon-thumbs-down"></span>
                <% end %>

                <span class="votes-count <%= votes_count_class %>">
                    <%= @votes_count.abs %>
                </span>
            </div>

            <br />
            <div>
                <% @picture.votes.each do |v| %>
                    <p><b><%= v.user.username %></b> gave <%= v.vote_type.to_i.positive? ? 'an upvote' : 'a downvote' %></p>
                <% end %>
            </div>
        </div>
    </div>

    <% if @is_owner %>
        <div class="panel panel-danger comments-panel">
            <div class="panel-heading">
                <h3 class="panel-title">Control</h3>
            </div>
            <div class="panel-body">
                <%= link_to('Delete this picture', {
                        :action=>"destroy",
                        :controller=>"pictures",
                        :user_id=>"#{@picture.user.id}",
                        :id=>"#{@picture.id}",
                    }, class: "btn btn-danger",
                    method: :delete, data: { confirm: "Do you really want to delete this picture?" })  %>
            </div>
        </div>
    <% end %>
</div>

app/views/users/_image_container.html.erb
<div class="image-container col-md-6" style="background: url(<%= " /uploads/#{p.path}" %>)" onclick="redirect('<%= url_for [current_user, p] %>')"></div>

app/views/users/mypictures.html.erb
<% provide(:title, 'My Pictures') %>

<h1>My Pictures</h1>

<% if !current_user.pictures.empty? %>
  <% current_user.pictures.each do |p| %>
      <%= render 'image_container', p: p %>
  <% end %>
<% else %>
  <div class="empty-message">
    <p>
      You don't have any pictures yet.
    </p>

    <p>
      You can upload some <%= link_to('here', pictures_new_path) %>
    </p>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Register') %>

<div class="form-container">
  <h1>Register</h1>

  <%= form_for @user do |f| %>
      <div class="error-zone">
          <% if @user != nil && @user.errors.any? %>
              <div id="error_explanation">
                  <h2>
                      Please solve <%= pluralize(@user.errors.count, "error") %> to register:
                  </h2>
                  <ul>
                      <% @user.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                      <% end %>
                  </ul>
              </div>
          <% end %>
      </div>

      <div class="form-group">
          <%= f.label :username %><br />
          <%= f.text_field :username, class: 'form-control' %>
      </div>

      <div class="form-group">
          <%= f.label :email %><br />
          <%= f.text_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
          <%= f.label :password %><br />
          <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
          <%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <div class="form-group">
          <%= f.button :submit, class: 'btn btn-primary' %>
      </div>
    <% end %>
</div>

app/views/users/profile.html.erb
<% provide(:title, 'Profile') %>

<div class="form-container">
    <% if @success_message %>
        <div class="alert alert-success" role="alert">
            <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            <%= @success_message %>
        </div>
    <% end %>

    <%= form_for(@user, :html => {class: "form-horizontal"}) do |f| %>
        <div class="form-group">
            <div class="col-sm-10 col-sm-offset-2">
                <h1>Profile of <%= @user.username %></h1>

                <div class="error-zone">
                    <% if @user != nil && @user.errors.any? %>
                        <div id="error_explanation">
                            <h2>
                                Please solve <%= pluralize(@user.errors.count, "error") %> to register:
                            </h2>
                            <ul>
                                <% @user.errors.full_messages.each do |msg| %>
                                    <li><%= msg %></li>
                                <% end %>
                            </ul>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :email, class: 'col-sm-2 control-label' %>
            <div class="col-sm-10">
                <%= f.text_field :email, class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit 'Save', class: "btn btn-default" %>
            </div>
        </div>


        <div class="form-group">
            <br />
            <br />
            <div class="col-sm-offset-2 col-sm-10">
            <%= link_to('Delete user account', { controller: "users", action: "destroy", id: @user },
                        class: 'btn btn-danger', method: :delete, data: { confirm: "Do you really want to delete yourself?" }) %>
            </div>
        </div>
    <% end %>
</div>